services:
  yfs1:
    build:
      context: .
      dockerfile: Dockerfile
    image: python-yfs
    networks:
      - yfs
    environment:
      - PID=1

  yfs2:
    image: python-yfs
    networks:
      - yfs
    environment:
      - PID=2
    depends_on:
      - yfs1

  yfs3:
    image: python-yfs
    networks:
      - yfs
    environment:
      - PID=3
    depends_on:
      - yfs1

  # yfs4:
  #   image: python-yfs
  #   networks:
  #     - yfs
  #   environment:
  #     - PID=4
  #   depends_on:
  #     - yfs1

  # yfs5:
  #   image: python-yfs
  #   networks:
  #     - yfs
  #   environment:
  #     - PID=5
  #   depends_on:
  #     - yfs1

networks:
  yfs:
    driver: bridge
