services:
  yfs1:
    build:
      context: .
      dockerfile: Dockerfile
    image: python-yfs
    networks:
      - yfs
    environment:
      - PID=1
    env_file: .env
    volumes:
      - type: bind
        source: ./Dirs/Dir1
        target: /app/yfs/Dir1
      - type: bind
        source: ./Logs
        target: /app/yfs/Logs

  yfs2:
    image: python-yfs
    networks:
      - yfs
    environment:
      - PID=2
    env_file: .env
    depends_on:
      - yfs1
    volumes:
      - type: bind
        source: ./Dirs/Dir2
        target: /app/yfs/Dir2
      - type: bind
        source: ./Logs
        target: /app/yfs/Logs

  yfs3:
    image: python-yfs
    networks:
      - yfs
    environment:
      - PID=3
    env_file: .env
    depends_on:
      - yfs1
    volumes:
      - type: bind
        source: ./Dirs/Dir3
        target: /app/yfs/Dir3
      - type: bind
        source: ./Logs
        target: /app/yfs/Logs

  yfs4:
    image: python-yfs
    networks:
      - yfs
    environment:
      - PID=4
    env_file: .env
    depends_on:
      - yfs1
    volumes:
      - type: bind
        source: ./Dirs/Dir4
        target: /app/yfs/Dir4
      - type: bind
        source: ./Logs
        target: /app/yfs/Logs

  yfs5:
    image: python-yfs
    networks:
      - yfs
    environment:
      - PID=5
    env_file: .env
    depends_on:
      - yfs1
    volumes:
      - type: bind
        source: ./Dirs/Dir5
        target: /app/yfs/Dir5
      - type: bind
        source: ./Logs
        target: /app/yfs/Logs

networks:
  yfs:
    driver: bridge
